/**
 * @fileoverview gRPC-Web generated client stub for main
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.3
// source: songs.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as songs_pb from './songs_pb'; // proto import: "songs.proto"


export class SongServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorUploadSong = new grpcWeb.MethodDescriptor(
    '/main.SongService/UploadSong',
    grpcWeb.MethodType.UNARY,
    songs_pb.UploadSongRequest,
    songs_pb.UploadSongResponse,
    (request: songs_pb.UploadSongRequest) => {
      return request.serializeBinary();
    },
    songs_pb.UploadSongResponse.deserializeBinary
  );

  uploadSong(
    request: songs_pb.UploadSongRequest,
    metadata?: grpcWeb.Metadata | null): Promise<songs_pb.UploadSongResponse>;

  uploadSong(
    request: songs_pb.UploadSongRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: songs_pb.UploadSongResponse) => void): grpcWeb.ClientReadableStream<songs_pb.UploadSongResponse>;

  uploadSong(
    request: songs_pb.UploadSongRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: songs_pb.UploadSongResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/main.SongService/UploadSong',
        request,
        metadata || {},
        this.methodDescriptorUploadSong,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/main.SongService/UploadSong',
    request,
    metadata || {},
    this.methodDescriptorUploadSong);
  }

  methodDescriptorStreamSongFile = new grpcWeb.MethodDescriptor(
    '/main.SongService/StreamSongFile',
    grpcWeb.MethodType.SERVER_STREAMING,
    songs_pb.StreamSongFileRequest,
    songs_pb.StreamSongFileResponse,
    (request: songs_pb.StreamSongFileRequest) => {
      return request.serializeBinary();
    },
    songs_pb.StreamSongFileResponse.deserializeBinary
  );

  streamSongFile(
    request: songs_pb.StreamSongFileRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<songs_pb.StreamSongFileResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/main.SongService/StreamSongFile',
      request,
      metadata || {},
      this.methodDescriptorStreamSongFile);
  }

  methodDescriptorStreamAlbumCover = new grpcWeb.MethodDescriptor(
    '/main.SongService/StreamAlbumCover',
    grpcWeb.MethodType.SERVER_STREAMING,
    songs_pb.StreamAlbumCoverRequest,
    songs_pb.StreamAlbumCoverResponse,
    (request: songs_pb.StreamAlbumCoverRequest) => {
      return request.serializeBinary();
    },
    songs_pb.StreamAlbumCoverResponse.deserializeBinary
  );

  streamAlbumCover(
    request: songs_pb.StreamAlbumCoverRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<songs_pb.StreamAlbumCoverResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/main.SongService/StreamAlbumCover',
      request,
      metadata || {},
      this.methodDescriptorStreamAlbumCover);
  }

  methodDescriptorGetUserSongs = new grpcWeb.MethodDescriptor(
    '/main.SongService/GetUserSongs',
    grpcWeb.MethodType.UNARY,
    songs_pb.GetUserSongsRequest,
    songs_pb.GetUserSongsResponse,
    (request: songs_pb.GetUserSongsRequest) => {
      return request.serializeBinary();
    },
    songs_pb.GetUserSongsResponse.deserializeBinary
  );

  getUserSongs(
    request: songs_pb.GetUserSongsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<songs_pb.GetUserSongsResponse>;

  getUserSongs(
    request: songs_pb.GetUserSongsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: songs_pb.GetUserSongsResponse) => void): grpcWeb.ClientReadableStream<songs_pb.GetUserSongsResponse>;

  getUserSongs(
    request: songs_pb.GetUserSongsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: songs_pb.GetUserSongsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/main.SongService/GetUserSongs',
        request,
        metadata || {},
        this.methodDescriptorGetUserSongs,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/main.SongService/GetUserSongs',
    request,
    metadata || {},
    this.methodDescriptorGetUserSongs);
  }

  methodDescriptorGetAllSongs = new grpcWeb.MethodDescriptor(
    '/main.SongService/GetAllSongs',
    grpcWeb.MethodType.UNARY,
    songs_pb.GetAllSongsRequest,
    songs_pb.GetAllSongsResponse,
    (request: songs_pb.GetAllSongsRequest) => {
      return request.serializeBinary();
    },
    songs_pb.GetAllSongsResponse.deserializeBinary
  );

  getAllSongs(
    request: songs_pb.GetAllSongsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<songs_pb.GetAllSongsResponse>;

  getAllSongs(
    request: songs_pb.GetAllSongsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: songs_pb.GetAllSongsResponse) => void): grpcWeb.ClientReadableStream<songs_pb.GetAllSongsResponse>;

  getAllSongs(
    request: songs_pb.GetAllSongsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: songs_pb.GetAllSongsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/main.SongService/GetAllSongs',
        request,
        metadata || {},
        this.methodDescriptorGetAllSongs,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/main.SongService/GetAllSongs',
    request,
    metadata || {},
    this.methodDescriptorGetAllSongs);
  }

  methodDescriptorUpdateSongMetadata = new grpcWeb.MethodDescriptor(
    '/main.SongService/UpdateSongMetadata',
    grpcWeb.MethodType.UNARY,
    songs_pb.UpdateSongMetadataRequest,
    songs_pb.UpdateSongMetadataResponse,
    (request: songs_pb.UpdateSongMetadataRequest) => {
      return request.serializeBinary();
    },
    songs_pb.UpdateSongMetadataResponse.deserializeBinary
  );

  updateSongMetadata(
    request: songs_pb.UpdateSongMetadataRequest,
    metadata?: grpcWeb.Metadata | null): Promise<songs_pb.UpdateSongMetadataResponse>;

  updateSongMetadata(
    request: songs_pb.UpdateSongMetadataRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: songs_pb.UpdateSongMetadataResponse) => void): grpcWeb.ClientReadableStream<songs_pb.UpdateSongMetadataResponse>;

  updateSongMetadata(
    request: songs_pb.UpdateSongMetadataRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: songs_pb.UpdateSongMetadataResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/main.SongService/UpdateSongMetadata',
        request,
        metadata || {},
        this.methodDescriptorUpdateSongMetadata,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/main.SongService/UpdateSongMetadata',
    request,
    metadata || {},
    this.methodDescriptorUpdateSongMetadata);
  }

  methodDescriptorDeleteSong = new grpcWeb.MethodDescriptor(
    '/main.SongService/DeleteSong',
    grpcWeb.MethodType.UNARY,
    songs_pb.DeleteSongRequest,
    songs_pb.DeleteSongResponse,
    (request: songs_pb.DeleteSongRequest) => {
      return request.serializeBinary();
    },
    songs_pb.DeleteSongResponse.deserializeBinary
  );

  deleteSong(
    request: songs_pb.DeleteSongRequest,
    metadata?: grpcWeb.Metadata | null): Promise<songs_pb.DeleteSongResponse>;

  deleteSong(
    request: songs_pb.DeleteSongRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: songs_pb.DeleteSongResponse) => void): grpcWeb.ClientReadableStream<songs_pb.DeleteSongResponse>;

  deleteSong(
    request: songs_pb.DeleteSongRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: songs_pb.DeleteSongResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/main.SongService/DeleteSong',
        request,
        metadata || {},
        this.methodDescriptorDeleteSong,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/main.SongService/DeleteSong',
    request,
    metadata || {},
    this.methodDescriptorDeleteSong);
  }

}

